*---------------------------------------------------------------------*
*    view related FORM routines
*   generation date: 23.04.2021 at 09:12:31
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*...processing: ZAPD_V003_2.....................................*
FORM GET_DATA_ZAPD_V003_2.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZCA_T_FLDS_VIEW WHERE
    APPL EQ 'ZAPD' AND
(VIM_WHERETAB) .
    CLEAR ZAPD_V003_2 .
ZAPD_V003_2-MANDT =
ZCA_T_FLDS_VIEW-MANDT .
ZAPD_V003_2-APPL =
ZCA_T_FLDS_VIEW-APPL .
ZAPD_V003_2-ID_VIEW =
ZCA_T_FLDS_VIEW-ID_VIEW .
ZAPD_V003_2-FLDNAME =
ZCA_T_FLDS_VIEW-FLDNAME .
ZAPD_V003_2-POS =
ZCA_T_FLDS_VIEW-POS .
ZAPD_V003_2-FLDNAME_INT =
ZCA_T_FLDS_VIEW-FLDNAME_INT .
ZAPD_V003_2-SENDUI5 =
ZCA_T_FLDS_VIEW-SENDUI5 .
ZAPD_V003_2-NO_VISIBLE =
ZCA_T_FLDS_VIEW-NO_VISIBLE .
    SELECT SINGLE * FROM ZCA_T_FLDS_VIEWT WHERE
APPL = ZCA_T_FLDS_VIEW-APPL AND
ID_VIEW = ZCA_T_FLDS_VIEW-ID_VIEW AND
FLDNAME = ZCA_T_FLDS_VIEW-FLDNAME AND
SPRAS = SY-LANGU .
    IF SY-SUBRC EQ 0.
ZAPD_V003_2-TXT_COLUMN =
ZCA_T_FLDS_VIEWT-TXT_COLUMN .
ZAPD_V003_2-TXT_INFO =
ZCA_T_FLDS_VIEWT-TXT_INFO .
    ENDIF.
    SELECT SINGLE * FROM ZAPD_T003 WHERE
APPL = ZCA_T_FLDS_VIEW-APPL AND
ID_VIEW = ZCA_T_FLDS_VIEW-ID_VIEW AND
FLDNAME = ZCA_T_FLDS_VIEW-FLDNAME .
    IF SY-SUBRC EQ 0.
ZAPD_V003_2-SHOW_HEADER =
ZAPD_T003-SHOW_HEADER .
ZAPD_V003_2-STYLE =
ZAPD_T003-STYLE .
ZAPD_V003_2-CAN_ORDER =
ZAPD_T003-CAN_ORDER .
ZAPD_V003_2-CAN_FILTER =
ZAPD_T003-CAN_FILTER .
ZAPD_V003_2-EMPTY_FIELD =
ZAPD_T003-EMPTY_FIELD .
ZAPD_V003_2-SHOW_LABEL =
ZAPD_T003-SHOW_LABEL .
    ENDIF.
<VIM_TOTAL_STRUC> = ZAPD_V003_2.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZAPD_V003_2 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZAPD_V003_2.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZAPD_V003_2-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZCA_T_FLDS_VIEW WHERE
  APPL = ZAPD_V003_2-APPL AND
  ID_VIEW = ZAPD_V003_2-ID_VIEW AND
  FLDNAME = ZAPD_V003_2-FLDNAME .
    IF SY-SUBRC = 0.
    DELETE ZCA_T_FLDS_VIEW .
    ENDIF.
    DELETE FROM ZCA_T_FLDS_VIEWT WHERE
    APPL = ZCA_T_FLDS_VIEW-APPL AND
    ID_VIEW = ZCA_T_FLDS_VIEW-ID_VIEW AND
    FLDNAME = ZCA_T_FLDS_VIEW-FLDNAME .
    SELECT SINGLE FOR UPDATE * FROM ZAPD_T003 WHERE
    APPL = ZCA_T_FLDS_VIEW-APPL AND
    ID_VIEW = ZCA_T_FLDS_VIEW-ID_VIEW AND
    FLDNAME = ZCA_T_FLDS_VIEW-FLDNAME .
    IF SY-SUBRC = 0.
    DELETE ZAPD_T003 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZCA_T_FLDS_VIEW WHERE
  APPL = ZAPD_V003_2-APPL AND
  ID_VIEW = ZAPD_V003_2-ID_VIEW AND
  FLDNAME = ZAPD_V003_2-FLDNAME .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZCA_T_FLDS_VIEW.
    ENDIF.
ZCA_T_FLDS_VIEW-MANDT =
ZAPD_V003_2-MANDT .
ZCA_T_FLDS_VIEW-APPL =
ZAPD_V003_2-APPL .
ZCA_T_FLDS_VIEW-ID_VIEW =
ZAPD_V003_2-ID_VIEW .
ZCA_T_FLDS_VIEW-FLDNAME =
ZAPD_V003_2-FLDNAME .
ZCA_T_FLDS_VIEW-POS =
ZAPD_V003_2-POS .
ZCA_T_FLDS_VIEW-FLDNAME_INT =
ZAPD_V003_2-FLDNAME_INT .
ZCA_T_FLDS_VIEW-SENDUI5 =
ZAPD_V003_2-SENDUI5 .
ZCA_T_FLDS_VIEW-NO_VISIBLE =
ZAPD_V003_2-NO_VISIBLE .
    IF SY-SUBRC = 0.
    UPDATE ZCA_T_FLDS_VIEW ##WARN_OK.
    ELSE.
    INSERT ZCA_T_FLDS_VIEW .
    ENDIF.
    SELECT SINGLE FOR UPDATE * FROM ZCA_T_FLDS_VIEWT WHERE
    APPL = ZCA_T_FLDS_VIEW-APPL AND
    ID_VIEW = ZCA_T_FLDS_VIEW-ID_VIEW AND
    FLDNAME = ZCA_T_FLDS_VIEW-FLDNAME AND
    SPRAS = SY-LANGU .
      IF SY-SUBRC <> 0.   "insert preprocessing: init WA
        CLEAR ZCA_T_FLDS_VIEWT.
ZCA_T_FLDS_VIEWT-APPL =
ZCA_T_FLDS_VIEW-APPL .
ZCA_T_FLDS_VIEWT-ID_VIEW =
ZCA_T_FLDS_VIEW-ID_VIEW .
ZCA_T_FLDS_VIEWT-FLDNAME =
ZCA_T_FLDS_VIEW-FLDNAME .
ZCA_T_FLDS_VIEWT-SPRAS =
SY-LANGU .
      ENDIF.
ZCA_T_FLDS_VIEWT-TXT_COLUMN =
ZAPD_V003_2-TXT_COLUMN .
ZCA_T_FLDS_VIEWT-TXT_INFO =
ZAPD_V003_2-TXT_INFO .
    IF SY-SUBRC = 0.
    UPDATE ZCA_T_FLDS_VIEWT ##WARN_OK.
    ELSE.
    INSERT ZCA_T_FLDS_VIEWT .
    ENDIF.
    SELECT SINGLE FOR UPDATE * FROM ZAPD_T003 WHERE
    APPL = ZCA_T_FLDS_VIEW-APPL AND
    ID_VIEW = ZCA_T_FLDS_VIEW-ID_VIEW AND
    FLDNAME = ZCA_T_FLDS_VIEW-FLDNAME .
      IF SY-SUBRC <> 0.   "insert preprocessing: init WA
        CLEAR ZAPD_T003.
ZAPD_T003-APPL =
ZCA_T_FLDS_VIEW-APPL .
ZAPD_T003-ID_VIEW =
ZCA_T_FLDS_VIEW-ID_VIEW .
ZAPD_T003-FLDNAME =
ZCA_T_FLDS_VIEW-FLDNAME .
      ENDIF.
ZAPD_T003-SHOW_HEADER =
ZAPD_V003_2-SHOW_HEADER .
ZAPD_T003-STYLE =
ZAPD_V003_2-STYLE .
ZAPD_T003-CAN_ORDER =
ZAPD_V003_2-CAN_ORDER .
ZAPD_T003-CAN_FILTER =
ZAPD_V003_2-CAN_FILTER .
ZAPD_T003-EMPTY_FIELD =
ZAPD_V003_2-EMPTY_FIELD .
ZAPD_T003-SHOW_LABEL =
ZAPD_V003_2-SHOW_LABEL .
    IF SY-SUBRC = 0.
    UPDATE ZAPD_T003 ##WARN_OK.
    ELSE.
    INSERT ZAPD_T003 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZAPD_V003_2-UPD_FLAG,
STATUS_ZAPD_V003_2-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZAPD_V003_2.
  SELECT SINGLE * FROM ZCA_T_FLDS_VIEW WHERE
APPL = ZAPD_V003_2-APPL AND
ID_VIEW = ZAPD_V003_2-ID_VIEW AND
FLDNAME = ZAPD_V003_2-FLDNAME .
ZAPD_V003_2-MANDT =
ZCA_T_FLDS_VIEW-MANDT .
ZAPD_V003_2-APPL =
ZCA_T_FLDS_VIEW-APPL .
ZAPD_V003_2-ID_VIEW =
ZCA_T_FLDS_VIEW-ID_VIEW .
ZAPD_V003_2-FLDNAME =
ZCA_T_FLDS_VIEW-FLDNAME .
ZAPD_V003_2-POS =
ZCA_T_FLDS_VIEW-POS .
ZAPD_V003_2-FLDNAME_INT =
ZCA_T_FLDS_VIEW-FLDNAME_INT .
ZAPD_V003_2-SENDUI5 =
ZCA_T_FLDS_VIEW-SENDUI5 .
ZAPD_V003_2-NO_VISIBLE =
ZCA_T_FLDS_VIEW-NO_VISIBLE .
    SELECT SINGLE * FROM ZCA_T_FLDS_VIEWT WHERE
APPL = ZCA_T_FLDS_VIEW-APPL AND
ID_VIEW = ZCA_T_FLDS_VIEW-ID_VIEW AND
FLDNAME = ZCA_T_FLDS_VIEW-FLDNAME AND
SPRAS = SY-LANGU .
    IF SY-SUBRC EQ 0.
ZAPD_V003_2-TXT_COLUMN =
ZCA_T_FLDS_VIEWT-TXT_COLUMN .
ZAPD_V003_2-TXT_INFO =
ZCA_T_FLDS_VIEWT-TXT_INFO .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZAPD_V003_2-TXT_COLUMN .
      CLEAR ZAPD_V003_2-TXT_INFO .
    ENDIF.
    SELECT SINGLE * FROM ZAPD_T003 WHERE
APPL = ZCA_T_FLDS_VIEW-APPL AND
ID_VIEW = ZCA_T_FLDS_VIEW-ID_VIEW AND
FLDNAME = ZCA_T_FLDS_VIEW-FLDNAME .
    IF SY-SUBRC EQ 0.
ZAPD_V003_2-SHOW_HEADER =
ZAPD_T003-SHOW_HEADER .
ZAPD_V003_2-STYLE =
ZAPD_T003-STYLE .
ZAPD_V003_2-CAN_ORDER =
ZAPD_T003-CAN_ORDER .
ZAPD_V003_2-CAN_FILTER =
ZAPD_T003-CAN_FILTER .
ZAPD_V003_2-EMPTY_FIELD =
ZAPD_T003-EMPTY_FIELD .
ZAPD_V003_2-SHOW_LABEL =
ZAPD_T003-SHOW_LABEL .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZAPD_V003_2-SHOW_HEADER .
      CLEAR ZAPD_V003_2-STYLE .
      CLEAR ZAPD_V003_2-CAN_ORDER .
      CLEAR ZAPD_V003_2-CAN_FILTER .
      CLEAR ZAPD_V003_2-EMPTY_FIELD .
      CLEAR ZAPD_V003_2-SHOW_LABEL .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZAPD_V003_2 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZAPD_V003_2-APPL TO
ZCA_T_FLDS_VIEW-APPL .
MOVE ZAPD_V003_2-ID_VIEW TO
ZCA_T_FLDS_VIEW-ID_VIEW .
MOVE ZAPD_V003_2-FLDNAME TO
ZCA_T_FLDS_VIEW-FLDNAME .
MOVE ZAPD_V003_2-MANDT TO
ZCA_T_FLDS_VIEW-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZCA_T_FLDS_VIEW'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZCA_T_FLDS_VIEW TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZCA_T_FLDS_VIEW'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

MOVE ZCA_T_FLDS_VIEW-APPL TO
ZCA_T_FLDS_VIEWT-APPL .
MOVE ZCA_T_FLDS_VIEW-ID_VIEW TO
ZCA_T_FLDS_VIEWT-ID_VIEW .
MOVE ZCA_T_FLDS_VIEW-FLDNAME TO
ZCA_T_FLDS_VIEWT-FLDNAME .
MOVE SY-LANGU TO
ZCA_T_FLDS_VIEWT-SPRAS .
MOVE ZAPD_V003_2-MANDT TO
ZCA_T_FLDS_VIEWT-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZCA_T_FLDS_VIEWT'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZCA_T_FLDS_VIEWT TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZCA_T_FLDS_VIEWT'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

MOVE ZCA_T_FLDS_VIEW-APPL TO
ZAPD_T003-APPL .
MOVE ZCA_T_FLDS_VIEW-ID_VIEW TO
ZAPD_T003-ID_VIEW .
MOVE ZCA_T_FLDS_VIEW-FLDNAME TO
ZAPD_T003-FLDNAME .
MOVE ZAPD_V003_2-MANDT TO
ZAPD_T003-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZAPD_T003'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZAPD_T003 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZAPD_T003'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
